"""
AgentForge - The Architect
Master planner, breaks complex goals into executable subtasks.
"""
import asyncio
import re
from typing import Any, Dict, List
from core.base import BaseAgent, AgentConfig, AgentType, Task
from core.llm import llm_manager


class Architect(BaseAgent):
    """The Planner - expert at breaking down complex problems"""
    
    def __init__(self, config: AgentConfig, memory, tool_registry):
        super().__init__(config, memory, tool_registry)
        self.planning_framework = "stepwise"
        self.llm_enabled = True
    
    async def think(self, prompt: str, context: Dict = None) -> str:
        """Think through a problem and create a plan"""
        system_prompt = f"""You are {self.name}, {self.personality}

Your role: {self.role}
You are a master strategist. When given a goal, break it down into clear, actionable steps.

Response format:
- Number each step
- Keep steps atomic and actionable
- Consider dependencies between steps
- Identify potential risks
"""
        full_prompt = f"{system_prompt}\n\nGoal: {prompt}\n\nContext: {context or {}}"
        
        # Try LLM first, fallback to simulation
        if self.llm_enabled:
            try:
                response = await llm_manager.chat([
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Break down this goal into steps: {prompt}"}
                ], provider="ollama")
                
                if response and not response.startswith("Error"):
                    self.memory.store_memory(
                        self.id, "thinking", prompt,
                        {"task": prompt, "framework": self.planning_framework}
                    )
                    return response
            except Exception:
                pass
        
        # Fallback
        response = await self._simulate_thinking(prompt)
        
        # Store in memory
        self.memory.store_memory(
            self.id, "thinking", prompt,
            {"task": prompt, "framework": self.planning_framework}
        )
        
        return response
    
    async def _execute_task(self, task: Task) -> Any:
        """Execute planning task"""
        if not task.subtasks:
            # Decompose the task
            subtasks = await self.decompose(task.description)
            task.subtasks = [Task(description=s) for s in subtasks]
        
        return {
            "plan": [s.description for s in task.subtasks],
            "total_steps": len(task.subtasks),
            "executor": self.name
        }
    
    async def decompose(self, goal: str) -> List[str]:
        """Break a goal into subtasks"""
        # Simulated decomposition - in production would use LLM
        steps = [
            f"Analyze requirements for: {goal}",
            f"Identify dependencies and constraints",
            f"Create implementation roadmap",
            f"Define success criteria",
            f"Execute primary task",
            f"Validate and test results"
        ]
        
        # Simple keyword detection for more specific decomposition
        goal_lower = goal.lower()
        
        if "build" in goal_lower or "create" in goal_lower:
            steps = [
                "Define specifications and requirements",
                "Design architecture and data models",
                "Set up project structure",
                "Implement core functionality",
                "Add tests and validation",
                "Deploy and verify"
            ]
        elif "research" in goal_lower or "find" in goal_lower:
            steps = [
                "Define research questions",
                "Identify information sources",
                "Gather and analyze data",
                "Synthesize findings",
                "Create summary report"
            ]
        
        return steps
    
    async def _simulate_thinking(self, prompt: str) -> str:
        """Simulate LLM thinking - replace with actual LLM call"""
        await asyncio.sleep(0.1)
        
        return f"""## Strategic Plan

Based on the goal, here's my approach:

1. **Analyze Requirements** - Understand the core objective and constraints
2. **Break Down** - Divide into atomic, executable steps
3. **Prioritize** - Order steps by dependency and impact
4. **Execute** - Begin with highest priority items
5. **Validate** - Verify each step meets success criteria

*This plan was generated by {self.name}*"""
