"""
AgentForge - The Builder
Writes and executes code.
"""
import asyncio
import subprocess
from typing import Any, Dict
from core.base import BaseAgent, AgentConfig, AgentType, Task
from core.llm import llm_manager


class Builder(BaseAgent):
    """The Builder - expert coder and software architect"""
    
    def __init__(self, config: AgentConfig, memory, tool_registry):
        super().__init__(config, memory, tool_registry)
        self.code_review_enabled = True
        self.llm_enabled = True
    
    async def think(self, prompt: str, context: Dict = None) -> str:
        """Think through code implementation"""
        system_prompt = f"""You are {self.name}, {self.personality}

Your role: {self.role}
You write clean, efficient, production-ready code.

Coding principles:
1. Write readable, maintainable code
2. Handle errors gracefully
3. Follow best practices
4. Test thoroughly
"""
        if self.llm_enabled:
            try:
                response = await llm_manager.chat([
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Write code for: {prompt}"}
                ], provider="ollama")
                
                if response and not response.startswith("Error"):
                    self.memory.store_memory(
                        self.id, "coding", prompt,
                        {"task": prompt, "review_enabled": self.code_review_enabled}
                    )
                    return response
            except Exception:
                pass
        
        response = await self._simulate_coding(prompt)
        
        self.memory.store_memory(
            self.id, "coding", prompt,
            {"task": prompt, "review_enabled": self.code_review_enabled}
        )
        
        return response
    
    async def _execute_task(self, task: Task) -> Any:
        """Execute coding task"""
        code = await self.write_code(task.description)
        
        # Execute if possible
        result = None
        if self.can_use_tool("execute_code"):
            result = await self.use_tool("execute_code", code=code)
        
        return {
            "code": code,
            "language": "python",
            "executed": result is not None,
            "result": result,
            "builder": self.name
        }
    
    async def write_code(self, requirement: str) -> str:
        """Write code based on requirement"""
        # Check if code execution tool is available
        if self.can_use_tool("code_generator"):
            code = await self.use_tool("code_generator", requirement=requirement)
            return code
        
        # Simulated code generation
        await asyncio.sleep(0.2)
        
        return f'''"""
Auto-generated code for: {requirement}
Generated by {self.name}
"""
import asyncio
from typing import Any, Dict, List

def main():
    # Implementation for: {requirement}
    result = {{
        "status": "success",
        "message": "Task completed",
        "data": None
    }}
    return result

if __name__ == "__main__":
    asyncio.run(main())
'''
    
    async def review_code(self, code: str) -> Dict:
        """Review code for issues"""
        await asyncio.sleep(0.1)
        
        issues = []
        
        # Basic checks
        if "eval(" in code or "exec(" in code:
            issues.append({"severity": "high", "message": "Avoid eval/exec - security risk"})
        
        if "except:" in code:
            issues.append({"severity": "medium", "message": "Use specific exception types"})
        
        if len(code) > 1000:
            issues.append({"severity": "low", "message": "Consider breaking into smaller functions"})
        
        return {
            "issues_found": len(issues),
            "issues": issues,
            "quality_score": max(0, 100 - len(issues) * 20)
        }
    
    async def execute_code(self, code: str) -> Dict:
        """Execute code and return results"""
        try:
            # In production, use sandboxed execution
            result = subprocess.run(
                ["python3", "-c", code],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            return {
                "success": result.returncode == 0,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "returncode": result.returncode
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    async def _simulate_coding(self, prompt: str) -> str:
        """Simulate coding - replace with actual LLM"""
        await asyncio.sleep(0.1)
        
        return f"""## Code Implementation

### Approach
1. Understand the requirements
2. Design the solution
3. Implement with best practices
4. Add error handling

### Code Structure
```python
# Clean, documented, production-ready code
# Following PEP 8 and best practices
```

*Code written by {self.name}*"""
