"""
AgentForge - The Sage
Analytics, reports, and insights.
"""
import asyncio
from typing import Any, Dict, List
from datetime import datetime
from core.base import BaseAgent, AgentConfig, AgentType, Task


class Sage(BaseAgent):
    """The Sage - data analyst and insight generator"""
    
    def __init__(self, config: AgentConfig, memory, tool_registry):
        super().__init__(config, memory, tool_registry)
        self.analysis_framework = "data-driven"
    
    async def think(self, prompt: str, context: Dict = None) -> str:
        """Analyze data and generate insights"""
        system_prompt = f"""You are {self.name}, {self.personality}

Your role: {self.role}
You transform data into actionable insights and clear reports.

Analysis approach:
1. Gather relevant data
2. Identify patterns and trends
3. Generate insights
4. Present recommendations

Task: {prompt}

{"Context: " + str(context) if context else ""}
"""
        response = await self._simulate_analysis(system_prompt)
        
        self.memory.store_memory(
            self.id, "analysis", prompt,
            {"task": prompt, "framework": self.analysis_framework}
        )
        
        return response
    
    async def _execute_task(self, task: Task) -> Any:
        """Execute analysis task"""
        report = await self.analyze(task.description)
        
        return {
            "report": report,
            "format": "markdown",
            "analyst": self.name,
            "generated_at": datetime.now().isoformat()
        }
    
    async def analyze(self, data: str) -> Dict:
        """Analyze data and generate insights"""
        await asyncio.sleep(0.2)
        
        # Check for data analysis tools
        if self.can_use_tool("data_analysis"):
            results = await self.use_tool("data_analysis", data=data)
            return results
        
        # Simulated analysis
        return {
            "summary": f"Analysis of: {data}",
            "key_metrics": {
                "total_items": 100,
                "success_rate": 0.85,
                "growth": "+15%"
            },
            "patterns": [
                "Pattern 1: Increasing trend",
                "Pattern 2: High engagement",
                "Pattern 3: Stable performance"
            ],
            "insights": [
                "Strong performance in primary metrics",
                "Room for improvement in secondary areas",
                "Recommendation: Focus on X"
            ],
            "recommendations": [
                "Continue current strategy",
                "Investigate area Y",
                "Optimize process Z"
            ]
        }
    
    async def create_report(self, data: Dict, format: str = "markdown") -> str:
        """Create formatted report"""
        await asyncio.sleep(0.1)
        
        if format == "markdown":
            return f"""# Analysis Report
Generated by {self.name}
Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Summary
{data.get('summary', 'No summary available')}

## Key Metrics
{self._format_metrics(data.get('key_metrics', {}))}

## Insights
{self._format_list(data.get('insights', []))}

## Recommendations
{self._format_list(data.get('recommendations', []))}

---
*Report generated by AgentForge - The Sage*
"""
        return str(data)
    
    def _format_metrics(self, metrics: Dict) -> str:
        return "\n".join([f"- **{k}**: {v}" for k, v in metrics.items()])
    
    def _format_list(self, items: List) -> str:
        return "\n".join([f"{i+1}. {item}" for i, item in enumerate(items)])
    
    async def generate_dashboard(self, metrics: Dict) -> Dict:
        """Generate dashboard data"""
        return {
            "widgets": [
                {"type": "metric", "label": "Total", "value": metrics.get("total", 0)},
                {"type": "chart", "label": "Trend", "data": [10, 20, 30, 40, 50]},
                {"type": "list", "label": "Top Items", "data": ["Item A", "Item B", "Item C"]}
            ],
            "layout": "grid"
        }
    
    async def _simulate_analysis(self, prompt: str) -> str:
        """Simulate analysis thinking"""
        await asyncio.sleep(0.1)
        
        return f"""## Analysis Report

### Summary
Comprehensive analysis completed for the given data.

### Key Findings

**Metric 1**: Significant growth (+15%)
- Exceeded baseline expectations
- Consistent with historical trends

**Metric 2**: High engagement rate (85%)
- Strong user interaction
- Room for optimization

### Insights

1. Performance is strong in core areas
2. User retention is stable
3. Growth trajectory is positive

### Recommendations

- Maintain current focus
- Investigate optimization opportunities
- Scale successful strategies

*Analysis by {self.name}*"""
